### ISSUE TITLE
Autovacuum memory 

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql-website#11]
> Autovacuum must not be switched off because it ensures that the tables are frequently analysed. If your machine has very little memory, you might consider setting autovacuum_max_workers = 1 and reduce autovacuum_work_mem even further. **This will reduce the amount of memory that autovacuum takes away from the import process.**

(Bold added)

My recollection was that osm2pgsql turned of autovacuum on the tables when importing, so the second sentence is incorrect.

I want to double-check this, so assigning to myself.

**Comment by joto** [comment]
Autovacuum is disabled only for temporary output tables, so that depends on the exact settings. Autovacuum is not generally disabled, so it will at the very least still affect the middle tables.
