### ISSUE TITLE
Documentation about osm2pgsql-replication appears to be misleading

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/osm2pgsql-website#17]
https://osm2pgsql.org/doc/install.html
says

    For Ubuntu installation is usually as simple as
    apt install osm2pgsql

and as expected on Ubuntu 21.04 

    osm2pgsql -V
    2021-10-31 14:30:38  osm2pgsql version 1.4.1

https://osm2pgsql.org/doc/manual.html#updating-an-existing-database
says

    Versions >1.4.1 Osm2pgsql comes with a script scripts/osm2pgsql-replication which is the easiest way to keep an osm2pgsql database up to date.

However, osm2pgsql-replication appears to be missing.

Is this a documentation issue or a packaging for debian/ubuntu issue, or something else?  https://packages.ubuntu.com/hirsute/osm2pgsql doesn't suggest another package to install to get the missing bits.

**Comment by SomeoneElseOSM** [comment]
Actually, the problem appears to be a bit of all 3.

Firstly - when it says "Versions >1.4.1" it means "Versions >= 1.4.2".

This in turn implies "in no current stable release of Debian or Ubuntu" - https://tracker.debian.org/pkg/osm2pgsql says that it's in Debian Testing, but it's not even in Ubuntu 21.10: https://packages.ubuntu.com/impish/osm2pgsql .

Some "how to run" documentation will be needed, but that won't be an issue until  osm2pgsql-replication is actually released in stable distributions. https://osm2pgsql.org/doc/manual.html#updating-an-existing-database contains plenty that seems like it ought to be useful, but not enough to get started without a considerable amount of trial and error.

**Comment by joto** [comment]
> Firstly - when it says "Versions >1.4.1" it means "Versions >= 1.4.2".

Yes, those are the same. I have updated the manual to make this more clear.

> Some "how to run" documentation will be needed

It mentioned `--help` and I have now added a mention of the man page to the docs. 

Does this resolve your isse?

**Comment by lonvia** [comment]
I've added some more documentation in #18.

Note that the script works with any version of osm2pgsql, so you don't really need to wait for a released version.
