### ISSUE TITLE
Manual pages links not working on Android

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql-website#4]
For some reason, part of the links on the new osm2pgsql Manual pages do not seem to work on my Android 7 phone, while they do work without issues within Firefox on my Windows 10 pc. There is no error displayed, trying to click the visibly underlined links just does nothing. E.g. when on the https://osm2pgsql.org/news/2020/12/07/release-1.4.0.html "News" page, I cannot click the "documentation", "examples", "support" and "contributing" links in the first text line, while I can click the "the manual" link on the bottom, and many other links are working as well, so it is not really consistent which ones work or don't.

@joto 

I now checked if other https:// links work, but of course they do, since most pages nowadays use https, and I have had no issues with other webpages. I was using the Android version of Firefox, but have now also tried it on Chrome, and I see the same issue.

**Comment by joto** [comment]
I can reproduce the problem. On small screens the links are "covered" by something transparent. I'll look into it.

**Comment by mboeringa** [comment]
@joto, I can confirm this now works on my device as well, I no longer have issues clicking the links.
