### ISSUE TITLE
Properly indicate viewed links to the user

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/osm2pgsql-website#43]
Here, instead of the default purple link, the blog title -and 'Read more' link- turns black when the link has been viewed. The colour black, especially between coloured(blue) links, usually indicates the string is plaintext. The title is still a link however, so it should be differentiated as such.

![image](https://user-images.githubusercontent.com/67521919/209705135-6508b95d-e0d2-45ab-a66b-ceb09dc47475.png)

**Comment by joto** [comment]
I like it the way it is. Unless it is a headline, it is still underlined, so you can see its something you can click on.
